version: '3'
    
services:
  dgraph:
    image: dgraph/standalone:v20.03.0
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: node start.js
    volumes:
      - .:/document-cache
    ports:
      - "8000:8000"
    depends_on:
      - db