name: Hypha Document Cache

on:
  push:
    branches:
    - dev2
    - dev
    - master
    - feature/add-instrumentation

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set docker-image-name to testnet
        if: endsWith(github.ref, '/dev')
        run: |
          echo "::set-env name=DOCKER_IMAGE_NAME::document-cache-testnet"
      - name: Set docker-image-name to testnet2
        if: endsWith(github.ref, '/dev2')
        run: |
          echo "::set-env name=DOCKER_IMAGE_NAME::document-cache-testnet2"
      - name: Set docker-image-name to instrumentation
        if: endsWith(github.ref, '/feature/add-instrumentation')
        run: |
          echo "::set-env name=DOCKER_IMAGE_NAME::document-cache-instrumentation"
      - name: Set docker-image-name to mainnet
        if: endsWith(github.ref, '/master')
        run: |
          echo "::set-env name=DOCKER_IMAGE_NAME::document-cache-mainnet"
      - uses: actions/checkout@v2
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build
        run: docker build -t $DOCKER_IMAGE_NAME .
      - name: Tags
        run: |
          docker tag $DOCKER_IMAGE_NAME ${{ secrets.DOCKER_HUB_USER }}/$DOCKER_IMAGE_NAME:${{ github.sha }}
          docker tag $DOCKER_IMAGE_NAME ${{ secrets.DOCKER_HUB_USER }}/$DOCKER_IMAGE_NAME:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_HUB_USER }}/$DOCKER_IMAGE_NAME:${{ github.sha }}
          docker push ${{ secrets.DOCKER_HUB_USER }}/$DOCKER_IMAGE_NAME:latest
