name: Hypha Document Cache

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build
        run: docker build -t hypha-doc-cache .
      - name: Tags
        run: |
          docker tag hypha-doc-cache ${{ secrets.DOCKER_USER }}/hypha-doc-cache:${{ github.sha }}
          docker tag hypha-doc-cache ${{ secrets.DOCKER_USER }}/hypha-doc-cache:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/hypha-doc-cache:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/hypha-doc-cache:latest
