name: Hypha Document Cache

on:
  push:
    branches:
    - dev2
    - dev
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:      
      - name: Set docker-image-name
        run: |
          echo "DOCKER_IMAGE_NAME=document-cache:${{ github.branch }}" >> $GITHUB_ENV
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build
        run: docker build -t $DOCKER_IMAGE_NAME .
      - name: Tags
        run: |
          docker tag $DOCKER_IMAGE_NAME ${{ secrets.DOCKER_HUB_USER }}/$DOCKER_IMAGE_NAME:${{ github.sha }}
          docker tag $DOCKER_IMAGE_NAME ${{ secrets.DOCKER_HUB_USER }}/$DOCKER_IMAGE_NAME:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_HUB_USER }}/$DOCKER_IMAGE_NAME:${{ github.sha }}
          docker push ${{ secrets.DOCKER_HUB_USER }}/$DOCKER_IMAGE_NAME:latest
